# Generated by Django 3.2.16 on 2025-10-05 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20251005_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 5, 7, 57, 1, 297151, tzinfo=utc), verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 5, 7, 57, 1, 296592, tzinfo=utc), verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 5, 7, 57, 1, 298287, tzinfo=utc), verbose_name='Добавлено'),
        ),
    ]
